# Generated by Django 5.0.4 on 2026-04-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("requirements", models.TextField()),
                ("required_skills", models.JSONField(default=list)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("FULL_TIME", "Full Time"),
                            ("PART_TIME", "Part Time"),
                            ("REMOTE", "Remote"),
                            ("CONTRACT", "Contract"),
                        ],
                        default="FULL_TIME",
                        max_length=20,
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("ENTRY", "Entry Level"),
                            ("MID", "Mid Level"),
                            ("SENIOR", "Senior"),
                            ("LEAD", "Lead / Manager"),
                        ],
                        default="ENTRY",
                        max_length=10,
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("industry", models.CharField(max_length=100)),
                ("is_accessibility_friendly", models.BooleanField(default=False)),
                ("accessibility_features", models.JSONField(default=list)),
                ("salary_min", models.PositiveIntegerField(blank=True, null=True)),
                ("salary_max", models.PositiveIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("deadline", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
