# Generated by Django 5.0.4 on 2026-04-11 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ResourceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "verbose_name_plural": "Resource Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("ARTICLE", "Article"),
                            ("VIDEO", "Video"),
                            ("WEBINAR", "Webinar"),
                            ("GUIDE", "Guide"),
                            ("CHECKLIST", "Checklist"),
                        ],
                        default="ARTICLE",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(blank=True)),
                ("external_url", models.URLField(blank=True)),
                ("thumbnail", models.URLField(blank=True)),
                ("is_accessible_for_blind", models.BooleanField(default=True)),
                ("is_accessible_for_deaf", models.BooleanField(default=True)),
                ("has_sign_language_video", models.BooleanField(default=False)),
                ("has_audio_description", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resources",
                        to="resources.resourcecategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
