# Generated by Django 5.0.4 on 2026-04-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("APPLIED", "Applied"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("INTERVIEW_SCHEDULED", "Interview Scheduled"),
                            ("REJECTED", "Rejected"),
                            ("HIRED", "Hired"),
                        ],
                        default="APPLIED",
                        max_length=25,
                    ),
                ),
                ("cover_letter", models.TextField(blank=True)),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-applied_at"],
            },
        ),
    ]
