# Generated by Django 5.0.4 on 2026-04-11 21:08

import resumes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=resumes.models.resume_upload_path,
                        validators=[resumes.models.validate_resume_file],
                    ),
                ),
                ("version", models.PositiveSmallIntegerField(default=1)),
                ("is_primary", models.BooleanField(default=False)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-version"],
            },
        ),
        migrations.CreateModel(
            name="ResumeAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField(blank=True, null=True)),
                ("missing_skills", models.JSONField(default=list)),
                ("suggestions", models.JSONField(default=list)),
                ("role_compatibility", models.JSONField(default=dict)),
                ("improved_resume_text", models.TextField(blank=True)),
                ("analyzed_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
